name: Build and deploy the website
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get -yyq install bundler
      - uses: actions/checkout@v2
        with:
          submodules: true
          lfs: true
      - run: bundle install
      - name: Build website
        run: bundle exec jekyll build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
