name: Build and deploy the website
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: sudo apt-get -yyq install bundler
      - uses: actions/checkout@v2
        with:
          submodules: true
          lfs: true
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ hashFiles('**/Gemfile.lock') }}
      - name: Build and publish
        uses:  helaili/jekyll-action@2.0.4
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
